### PR TITLE
Extract GlobalRunner into a mini-library (Highlander)

### PR DESCRIPTION
**Pull request by derekkraan**
Hi @slashdotdash,

I decided to extract GlobalRunner into a mini-library (and fixed a bug in the process, that somehow didn't show up in the tests, _or_ in our production systems, or we didn't notice it).

I did this because as maintainer of Horde, the question I see most often is "how can I run a process just once in a cluster?". A lot of these people use Horde today, but that's overkill, something much smaller will suffice.

Cheers
Derek

### CODE REVIEW

**Comment by slashdotdash** [comment]
I added a test for the global supervisor for the v1.0.0 release branch and discovered an issue when the supervisor process was started concurrently on multiple nodes. The change I made was to add a [small random delay before attempting to restart the process](https://github.com/commanded/eventstore/blob/009b23d0549b59bd2e7e074f0439045071ca162d/lib/event_store/notifications/global_runner.ex#L18).

**Comment by derekkraan** [comment]
Ah yes. I think the issue here is that the Process.monitor part wasn't implemented correctly. It _should_ be fixed and just work :tm: in Highlander.

**Comment by derekkraan** [comment]
I'm not sure how I can run this test. Running mix test.all seems to generate a lot of postgres deadlocks :thinking:

**Comment by slashdotdash** [comment]
The distributed supervisor test is only in the `releases/v1.0.0` branch at the moment. It needs to be merged it into master first. Leave it with me and I will get it sorted and give the PR a try.

**Pull request merged**
