### PR TITLE
Use `timestamp with time zone` for timestamp fields.

### PR DESCRIPTION
**Pull request by datafoo**
This pull request address issue https://github.com/commanded/eventstore/issues/147.

### CODE REVIEW

**Comment by slashdotdash** [comment]
@datafoo Thanks for the pull request.

**Comment by datafoo** [comment]
Any plan to merge the pull request?

**Comment by slashdotdash** [comment]
@datafoo Merging this pull request will have an impact on Commanded since it currently uses `NaiveDateTime` for the recorded event struct's `created_at` field. 

This means either:

- Commanded EventStore adapter needs to be changed to map from `DateTime` to `NaiveDateTime` to remain compatible with Commanded;
- Commanded and supporting libraries all need to be updated to use `DateTime` instead of `NaiveDateTime` which will be a breaking change for any consumers (e.g. accessing `created_at` from event handler metadata).

**Comment by datafoo** [comment]
> Commanded and supporting libraries all need to be updated to use `DateTime` instead of `NaiveDateTime` which will be a breaking change for any consumers (e.g. accessing `created_at` from event handler metadata).

I would go for that solution. Can we agree on that?

**Comment by KazW** [comment]
@datafoo Just wondering, how would this change be helpful to the average user of Eventstore/Commanded? I haven't use Eventstore with anything other than Commanded, so I'm curious.

**Comment by slashdotdash** [comment]
@KazW There's a similar issue about `DateTime` vs. `NaiveDateTime` open for Commanded ([#252](https://github.com/commanded/commanded/issues/252)).

**Comment by datafoo** [comment]
> @datafoo Just wondering, how would this change be helpful to the average user of Eventstore/Commanded? I haven't use Eventstore with anything other than Commanded, so I'm curious.

It may not be helpful for the average user. However, it make the meaning of the data explicit on the database side, which is helpful for the curious user. For me, for example, when I inspect the database tables with pgAdmin, since PostgreSQL is aware of the semantic of a `timetamp with time zone` then I can display such a field in any time zone that I would like, instead on converting in my head.

**Comment by datafoo** [comment]
> * Commanded and **supporting libraries all need to be updated** to use `DateTime` instead of `NaiveDateTime` which will be a breaking change for any consumers (e.g. accessing `created_at` from event handler metadata).

Could you please list these "supporting libraries"?

**Comment by slashdotdash** [comment]
> Could you please list these "supporting libraries"?

To migrate just the event store adapters to use `DateTime` then the following libraries must be updated:

- [Commanded EventStore adapter](https://github.com/commanded/commanded-eventstore-adapter)
- [Commaned Extreme adapter](https://github.com/commanded/commanded-extreme-adapter)
- In-memory event store (included with Commanded)

If we decide to use `DateTime` instead of `NaiveDateTime` entirely then the following supporting libraries will also need to be updated:

- [Commanded audit middleware](https://github.com/commanded/commanded-audit-middleware)
- [Commanded scheduler](https://github.com/commanded/commanded-scheduler)
- [Commanded Ecto projections](https://github.com/commanded/commanded-ecto-projections)

**Pull request merged**
