### PR TITLE
Improve typespecs

### LINKED ISSUE #120: Wrong Typespecs
While integrating eventstore into our project we found some false typespecs in eventstore. Running `mix dialzyer` reveals that this project has some type errors.

```cli
👌  eventstore git:(master) mix dialyzer
Compiling 1 file (.ex)
Checking PLT...
[:credo, :dialyxir, :elixir, :ex_doc, :fsm, :gen_stage, :kernel, :logger,
 :markdown, :mix_test_watch, :poison, :poolboy, :postgrex, :stdlib, :uuid]
PLT is up to date!
Starting Dialyzer
dialyzer args: [
  check_plt: false,
  init_plt: '/Users/ole/projects/eventstore/_build/dev/dialyxir_erlang-20.3.7_elixir-1.6.5_deps-dev.plt',
  files_rec: ['/Users/ole/projects/eventstore/_build/dev/lib/eventstore/ebin'],
  warnings: [:unknown]
]
done in 2m0.78s
:0: Unknown function 'Elixir.DBConnection':execute/4
:0: Unknown function 'Elixir.DBConnection':prepare_execute/4
:0: Unknown function 'Elixir.DBConnection.Backoff':backoff/1
:0: Unknown function 'Elixir.DBConnection.Backoff':new/1
:0: Unknown function 'Elixir.Decimal':new/1
:0: Unknown function 'Elixir.Mix':raise/1
:0: Unknown function 'Elixir.Mix':shell/0
:0: Unknown function 'Elixir.Mix.Project':config/0
:0: Unknown function 'Elixir.Mix.Task':reenable/1
:0: Unknown type 'Elixir.RecodedEvent':t/0
:0: Unknown type 'Elixir.RecordedEvent':t/0
lib/event_store/storage/appender.ex:207: The pattern {'error', Vreason@1} can never match since previous clauses completely covered the type {'error',#{'__exception__':=_, '__struct__':='Elixir.Postgrex.Error', 'connection_id':=_, 'message':=_, 'postgres':=_}} | {'ok',#{'__struct__':='Elixir.Postgrex.Result', 'columns':='nil' | [any()], 'command':=atom(), 'connection_id':=pos_integer(), 'num_rows':=integer(), 'rows':='nil' | [any()]}}
lib/event_store/storage/appender.ex:208: The created fun has no local return
lib/event_store/subscriptions/subscription_fsm.ex:7: The pattern <_@1 = #{'__struct__':='Elixir.EventStore.Subscriptions.SubscriptionFsm'}, _> can never match since previous clauses completely covered the type <#{'__struct__':='Elixir.EventStore.Subscriptions.SubscriptionFsm', 'data':=_, 'state':=_, _=>_},{'action_responses',[{_,_},...]}>
lib/event_store/subscriptions/subscription_fsm.ex:282: Function try_acquire_exclusive_lock/1 has no local return
lib/event_store/subscriptions/subscription_fsm.ex:285: The call 'Elixir.EventStore.AdvisoryLocks':try_advisory_lock(Vsubscription_id@1::any(),[{'lock_reacquired',fun(() -> 'ok')} | {'lock_released',fun(() -> 'ok')},...]) breaks the contract (key::non_neg_integer(),opts::[]) -> 'ok' | {'error','lock_already_taken'} | {'error',term()}
lib/mix/tasks/event_store.create.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
lib/mix/tasks/event_store.drop.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
lib/mix/tasks/event_store.init.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
lib/mix/tasks/event_store.migrate.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
done (warnings were emitted)
```

I propose the following solution: I'd open a PR to fix the typespecs and add `mix dialzyer` to the ci pipeline so future commits that would break the typespecs will be spotted earlier.

Any thoughts on this?

### PR DESCRIPTION
**Pull request by OleMchls**
As described in #120 this PR addresses some typespec errors.

Thw work on this triggered two two tickets in their respective repos: https://github.com/sasa1977/fsm/issues/10 & https://github.com/jeremyjh/dialyxir/issues/192

---
fixes #120 

_Update 06/14/2018: removed fixed no return error_
_Update 06/14/2018: update to declare it ready to be merged_
_Update 06/14/2018: reflect updated fsm_

### CODE REVIEW

**Comment by slashdotdash** [comment]
Great work, thank you @OleMchls. I'll keep an eye on when you're ready for the PR to be merged.

**Comment by OleMchls** [comment]
@slashdotdash I fixed one warning and ignored the other, so I think this PR is good to be merged. I updated the initial ticket to reflect the current state.

Let me know if you have any feedback you would want to see addressed.

**Comment by OleMchls** [comment]
@slashdotdash Together with the incredible 🎉 @coreyhaines I fixed the last remaining build breaker. We also removed the ignored warning and rather had the issue fixed upstream in `fsm`.

**Comment by slashdotdash** [comment]
Thanks for taking the time to get this fixed @OleMchls.

**Pull request merged**
