### PR TITLE
Remove mentions of CQRS.

### LINKED ISSUE #151: [question] Why the term "CQRS event store" appears in this repository?
The term "CQRS event store" appears in 2 [occasions](https://github.com/commanded/eventstore/search?q=cqrs&unscoped_q=cqrs) in this repository.

Event though an event store is needed when using CQRS, I believe using this event store does not only apply to CQRS, isn't?

Should renaming "CQRS event store" to just "event store" better represent what this project is about?

### PR DESCRIPTION
**Pull request by datafoo**
Fixes #151.

### CODE REVIEW

**Comment by datafoo** [comment]
Can you also modify the `Description` field of the repository accordingly?

**Comment by slashdotdash** [comment]
> Can you also modify the `Description` field of the repository accordingly?

Done.

**Comment by datafoo** [comment]
Thanks, and also the [Home.md](https://github.com/commanded/eventstore/wiki) in the wiki?

**Comment by slashdotdash** [comment]
> Thanks, and also the [Home.md](https://github.com/commanded/eventstore/wiki) in the wiki?

Also done!

**Comment by datafoo** [comment]
> Also done!
Thank you!

**Pull request merged**
